services:
  api:
    image: dragonir/jfl-api:1.0.5
    environment:
      TZ: Europe/Paris
      TOKEN_FILE: /run/secrets/jfl-api-token
    secrets:
      - jfl-api-token
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5000:5000"
    volumes:
      - repo:/app/repo

  proxy:
    image: 'jc21/nginx-proxy-manager:2'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - portainer
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    healthcheck:
      test: "curl --fail http://localhost:81 || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - proxy-data:/data
      - proxy-certs:/etc/letsencrypt

  portainer:
    image: portainer/portainer-ce:linux-amd64
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  repo:
  portainer_data:
  proxy-data:
  proxy-certs:

secrets:
  jfl-api-token:
    file: ./secrets/jfl-api-token.txt